### ISSUE TITLE
圆孔特征位置识别

### ISSUE THREAD

**Issue by DR-dairy** [painezeng/CSharpAndSolidWorks#2]
请问老师，SolidWorks里面可以自动识别圆孔特征，并提取出  圆孔端面的圆心  相对全局坐标系的位置参数吗？（不通过点击选取圆心点）谢谢。

**Comment by painezeng** [comment]
遍历来解决呀

**Comment by DR-dairy** [comment]
我能通过遍历找到圆孔特征，和圆孔特征参数，但是我想提取圆孔端面的圆心的位置参数（相对于全局坐标系，或者该零件的某个点），相关函数接口我没找到，请问有办法解决吗？谢谢。

**Comment by painezeng** [comment]
请参考坐标转换，正常你获取到的圆就是相对于该零件的坐标系的。
