### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by yss0729** [painezeng/CSharpAndSolidWorks#3]
你好，我本地只安装了一个 SolidWorks 2012 API SDK.msi 

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0246	未能找到类型或命名空间名“DimXpertPart”(是否缺少 using 指令或程序集引用?)	CSharpAndSolidWorks	C:\Users\yss72\Downloads\CSharpAndSolidWorks-master\CSharpAndSolidWorks\FormMain.cs	4487	活动

还需要安装其他东西吗

**Comment by painezeng** [comment]
这个dll估计你没有，你可以把报错的地方删除，这里面只有一个例子用到这个库。
